# Generated by Django 5.2.1 on 2025-05-12 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(max_length=140)),
                ('goal_description', models.CharField(max_length=2000)),
                ('priority', models.IntegerField()),
                ('due_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('goal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='be.goal')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=140)),
                ('project_description', models.CharField(max_length=2000)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='be.project')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='be.user')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=140)),
                ('task_type', models.CharField(choices=[('1off', 'one-off completable task'), ('recc', 'recurring task'), ('note', 'note task (non completable)')], max_length=5)),
                ('task_description', models.CharField(max_length=2000)),
                ('due_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('priority', models.IntegerField()),
                ('is_completed', models.BooleanField()),
                ('recurrence_interval', models.DurationField()),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='be.task')),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='be.project')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='be.user')),
            ],
        ),
        migrations.AddField(
            model_name='goal',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='be.user'),
        ),
    ]
