# Generated by Django 5.2.1 on 2025-05-12 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be', '0002_alter_goalhistory_priority_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='be.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='be.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='recurrence_interval',
            field=models.DurationField(null=True),
        ),
    ]
