# Generated by Django 5.2.1 on 2025-05-12 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be', '0003_alter_task_parent_id_alter_task_project_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='be.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='be.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='recurrence_interval',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
